export const StadiumData = [
  {
    id: 0,
    Name: "Acrisure Stadium",
    Location: "Pittsburgh, Pennsylvania",
    Dome: "Open",
    Team: "Pittsburgh Steelers",
    Latitude: 40.4468,
    Longitude: -80.0158,
  },
  {
    id: 1,
    Name: "Allegiant Stadium",
    Location: "Las Vegas, Nevada",
    Dome: "Fixed",
    Team: "Las Vegas Raiders",
    Latitude: 36.0909,
    Longitude: -115.1833,
  },
  {
    id: 3,
    Name: "GEHA Field at Arrowhead Stadium",
    Location: "Kansas City, Missouri",
    Dome: "Open",
    Team: "Kansas City Chiefs",
    Latitude: 39.0489,
    Longitude: -94.4839,
  },
  {
    id: 4,
    Name: "AT&T Stadium",
    Location: "Arlington, Texas",
    Dome: "Retractable",
    Team: "Dallas Cowboys",
    Latitude: 32.7473,
    Longitude: -97.0945,
  },
  {
    id: 5,
    Name: "Bank of America Stadium",
    Location: "Charlotte, North Carolina",
    Dome: "Open",
    Team: "Carolina Panthers",
    Latitude: 35.2258,
    Longitude: -80.853,
  },
  {
    id: 6,
    Name: "Caesars Superdome",
    Location: "New Orleans, Louisiana",
    Dome: "Fixed",
    Team: "New Orleans Saints",
    Latitude: 29.9511,
    Longitude: -90.0812,
  },
  {
    id: 7,
    Name: "Empower Field at Mile High",
    Location: "Denver, Colorado",
    Dome: "Open",
    Team: "Denver Broncos",
    Latitude: 39.7439,
    Longitude: -105.0201,
  },
  {
    id: 8,
    Name: "FedEx Field",
    Location: "Landover, Maryland",
    Dome: "Open",
    Team: "Washington Commanders",
    Latitude: 38.9077,
    Longitude: -76.8645,
  },
  {
    id: 9,
    Name: "Ford Field",
    Location: "Detroit, Michigan",
    Dome: "Fixed",
    Team: "Detroit Lions",
    Latitude: 42.34,
    Longitude: -83.0456,
  },
  {
    id: 10,
    Name: "Gillette Stadium",
    Location: "Foxborough, Massachusetts",
    Dome: "Open",
    Team: "New England Patriots",
    Latitude: 42.0909,
    Longitude: -71.2643,
  },
  {
    id: 11,
    Name: "Hard Rock Stadium",
    Location: "Miami Gardens, Florida",
    Dome: "Open",
    Team: "Miami Dolphins",
    Latitude: 25.958,
    Longitude: -80.2389,
  },
  {
    id: 12,
    Name: "Highmark Stadium",
    Location: "Orchard Park, New York",
    Dome: "Open",
    Team: "Buffalo Bills",
    Latitude: 42.7738,
    Longitude: -78.787,
  },
  {
    id: 13,
    Name: "Lambeau Field",
    Location: "Green Bay, Wisconsin",
    Dome: "Open",
    Team: "Green Bay Packers",
    Latitude: 44.5013,
    Longitude: -88.0622,
  },
  {
    id: 14,
    Name: "Levi's Stadium",
    Location: "Santa Clara, California",
    Dome: "Open",
    Team: "San Francisco 49ers",
    Latitude: 37.4033,
    Longitude: -121.9694,
  },
  {
    id: 15,
    Name: "Lincoln Financial Field",
    Location: "Philadelphia, Pennsylvania",
    Dome: "Open",
    Team: "Philadelphia Eagles",
    Latitude: 39.9014,
    Longitude: -75.1675,
  },
  {
    id: 17,
    Name: "Lucas Oil Stadium",
    Location: "Indianapolis, Indiana",
    Dome: "Retractable",
    Team: "Indianapolis Colts",
    Latitude: 39.7601,
    Longitude: -86.1639,
  },
  {
    id: 18,
    Name: "Lumen Field",
    Location: "Seattle, Washington",
    Dome: "Open",
    Team: "Seattle Seahawks",
    Latitude: 47.5952,
    Longitude: -122.3316,
  },
  {
    id: 19,
    Name: "M&T Bank Stadium",
    Location: "Baltimore, Maryland",
    Dome: "Open",
    Team: "Baltimore Ravens",
    Latitude: 39.278,
    Longitude: -76.6227,
  },
  {
    id: 20,
    Name: "Mercedes-Benz",
    Location: "Atlanta, Georgia",
    Dome: "Retractable",
    Team: "Atlanta Falcons",
    Latitude: 33.7553,
    Longitude: -84.4006,
  },
  {
    id: 21,
    Name: "MetLife Stadium",
    Location: "East Rutherford, New Jersey",
    Dome: "Open",
    Team: ["New York Giants", "New York Jets"],
    Latitude: 40.8135,
    Longitude: -74.0745,
  },
  {
    id: 22,
    Name: "Nissan Stadium",
    Location: "Nashville, Tennessee",
    Dome: "Open",
    Team: "Tennessee Titans",
    Latitude: 36.1665,
    Longitude: -86.7713,
  },
  {
    id: 23,
    Name: "NRG Stadium",
    Location: "Houston, Texas",
    Dome: "Retractable",
    Team: "Houston Texans",
    Latitude: 29.6847,
    Longitude: -95.4107,
  },
  {
    id: 24,
    Name: "Paycor Stadium",
    Location: "Cincinnati, Ohio",
    Dome: "Open",
    Team: "Cincinnati Bengals",
    Latitude: 39.0955,
    Longitude: -84.5161,
  },
  {
    id: 25,
    Name: "Raymond James Stadium",
    Location: "Tampa, Florida",
    Dome: "Open",
    Team: "Tampa Bay Buccaneers",
    Latitude: 27.9759,
    Longitude: -82.5033,
  },
  {
    id: 26,
    Name: "SoFi Stadium",
    Location: "Inglewood, California",
    Dome: "Fixed",
    Team: ["Los Angeles Rams", "Los Angeles Chargers"],
    Latitude: 33.9535,
    Longitude: -118.339,
  },
  {
    id: 27,
    Name: "Soldier Field",
    Location: "Chicago, Illinois",
    Dome: "Open",
    Team: "Chicago Bears",
    Latitude: 41.8623,
    Longitude: -87.6167,
  },
  {
    id: 28,
    Name: "State Farm Stadium",
    Location: "Glendale, Arizona",
    Dome: "Retractable",
    Team: "Arizona Cardinals",
    Latitude: 33.5276,
    Longitude: -112.2626,
  },
  {
    id: 29,
    Name: "TIAA Bank Field",
    Location: "Jacksonville, Florida",
    Dome: "Open",
    Team: "Jacksonville Jaguars",
    Latitude: 30.3239,
    Longitude: -81.6373,
  },
  {
    id: 30,
    Name: "U.S. Bank Stadium",
    Location: "Minneapolis, Minnesota",
    Dome: "Fixed",
    Team: "Minnesota Vikings",
    Latitude: 44.9736,
    Longitude: -93.2575,
  },
  {
    id: 31,
    Name: "Tottenham Hotspur Stadium",
    Location: "London, England, United Kingdom",
    Dome: "Open",
    Team: "London England United Kingdom",
    Latitude: 51.6042,
    Longitude: -0.0662,
  },
  {
    id: 32,
    Name: "Allianz Arena",
    Location: "München, Germany",
    Dome: "Retractable",
    Team: "Munich Germany München",
    Latitude: 48.2188,
    Longitude: 11.6248,
  },
];
